apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: Homelab
    theme: dark
  services.yaml: |
    - Cluster:
        - Argo CD:
            href: http://localhost:8081
            description: GitOps
        - Podinfo:
            href: http://localhost:9898
            description: demo app
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: ""
